global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"

  - job_name: "spring-apps"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080", "host.docker.internal:6060"]
    scrape_interval: 10s

  - job_name: "kafka-ui"
    static_configs:
      - targets: ["kafka-ui:8080"]

  - job_name: "zipkin"
    static_configs:
      - targets: ["zipkin:9411"]