spring:
  application:
    name: inventory-service  # или auth-service, product-service, etc.
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/marketplace
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:29092
    # Настройки потребителя (Consumer)

    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#        spring.json.type.mapping: |
#          orderCreatedEvent:com.marketplace.common.events.order.OrderCreatedEvent,
#          productCreatedEvent:com.marketplace.common.events.product.ProductCreatedEvent

    # Настройки администрирования (создание топиков)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    properties:
      spring.json.trusted.packages: "*"
  

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
# Кастомные настройки Kafka
#app:
#  kafka:
#    topics:
#      order-created: "order-created"
#      product-created: "product-created"
#      inventory-reserved: "inventory-reserved"
server:
  port: 8040
#      payment-processed: "payment-processed"
management:
  tracing:
    sampling:
      probability: 1